### ISSUE TITLE
Planning library not loaded

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#70]
This is happening on multiple Trusty machines. Due to the missing planning libraries, no planning seems to be occurring.

```
$ dpkg -p ros-indigo-denso ros-indigo-pr2-controller-manager ros-indigo-moveit-planners|grep Ver
Version: 1.1.2-0trusty-20151221-1520-+0000
Version: 1.8.16-0trusty-20151204-1847-+0000
Version: 0.6.7-0trusty-20151201-1757-+0000

$ roslaunch vs060_moveit_config demo.launch 
... logging to /home/n130s/.ros/log/d4f99738-b4a2-11e5-8b7c-80fa5b08d1d8/roslaunch-tork-kudu1-16771.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://tork-kudu1:46900/

SUMMARY
========

PARAMETERS
 * /arm_controller/gains/flange/d: 0
 * /arm_controller/gains/flange/i: 0
 * /arm_controller/gains/flange/p: 1.0
 * /arm_controller/gains/j1/d: 0
 * /arm_controller/gains/j1/i: 0
 * /arm_controller/gains/j1/p: 1.0
 * /arm_controller/gains/j2/d: 0
 * /arm_controller/gains/j2/i: 0
 * /arm_controller/gains/j2/p: 1.0
 * /arm_controller/gains/j3/d: 0
 * /arm_controller/gains/j3/i: 0
 * /arm_controller/gains/j3/p: 1.0
 * /arm_controller/gains/j4/d: 0
 * /arm_controller/gains/j4/i: 0
 * /arm_controller/gains/j4/p: 1.0
 * /arm_controller/gains/j5/d: 0
 * /arm_controller/gains/j5/i: 0
 * /arm_controller/gains/j5/p: 1.0
 * /arm_controller/joint_trajectory_action_node/constraints/flange/goal: 0.02
 * /arm_controller/joint_trajectory_action_node/constraints/goal_time: 0.6
 * /arm_controller/joint_trajectory_action_node/constraints/j1/goal: 0.02
 * /arm_controller/joint_trajectory_action_node/constraints/j2/goal: 0.02
 * /arm_controller/joint_trajectory_action_node/constraints/j3/goal: 0.02
 * /arm_controller/joint_trajectory_action_node/constraints/j4/goal: 0.02
 * /arm_controller/joint_trajectory_action_node/constraints/j5/goal: 0.02
 * /arm_controller/joint_trajectory_action_node/joints: ['j1', 'j2', 'j3'...
 * /arm_controller/joints: ['j1', 'j2', 'j3'...
 * /arm_controller/type: robot_mechanism_c...
 * /move_group/allow_trajectory_execution: True
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'default': True...
 * /move_group/controller_manager_name: pr2_controller_ma...
 * /move_group/controller_manager_ns: pr2_controller_ma...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /move_group/manipulator/kinematics_solver_attempts: 3
 * /move_group/manipulator/kinematics_solver_search_resolution: 0.005
 * /move_group/manipulator/kinematics_solver_timeout: 0.5
 * /move_group/manipulator/longest_valid_segment_fraction: 0.05
 * /move_group/manipulator/planner_configs: ['SBLkConfigDefau...
 * /move_group/manipulator/projection_evaluator: joints(j1,j2)
 * /move_group/manipulator_flange/kinematics_solver: kdl_kinematics_pl...
 * /move_group/manipulator_flange/kinematics_solver_attempts: 3
 * /move_group/manipulator_flange/kinematics_solver_search_resolution: 0.005
 * /move_group/manipulator_flange/kinematics_solver_timeout: 0.005
 * /move_group/manipulator_flange/planner_configs: ['SBLkConfigDefau...
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: pr2_moveit_contro...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_frame: BASE
 * /move_group/octomap_resolution: 0.05
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/LazyRRTkConfigDefault/type: geometric::LazyRRT
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTStarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{'point_subsampl...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/use_controller_manager: True
 * /realtime_loop/min_acceptable_rt_loop_frequency: 100.0
 * /realtime_loop/not_sleep_clock: True
 * /realtime_loop/rt_period: 8000000.0
 * /realtime_loop/server_ip: 133.11.216.51
 * /realtime_loop/udp_timeout: 9000
 * /robot_description: <?xml version="1....
 * /robot_description_planning/joint_limits/flange/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/flange/has_velocity_limits: True
 * /robot_description_planning/joint_limits/flange/max_acceleration: 0.7
 * /robot_description_planning/joint_limits/flange/max_velocity: 0.7
 * /robot_description_planning/joint_limits/j1/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/j1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j1/max_acceleration: 0.7
 * /robot_description_planning/joint_limits/j1/max_velocity: 0.7
 * /robot_description_planning/joint_limits/j2/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/j2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2/max_acceleration: 0.7
 * /robot_description_planning/joint_limits/j2/max_velocity: 0.7
 * /robot_description_planning/joint_limits/j3/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/j3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j3/max_acceleration: 0.7
 * /robot_description_planning/joint_limits/j3/max_velocity: 0.7
 * /robot_description_planning/joint_limits/j4/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/j4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j4/max_acceleration: 0.5
 * /robot_description_planning/joint_limits/j4/max_velocity: 0.4
 * /robot_description_planning/joint_limits/j5/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/j5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j5/max_acceleration: 0.7
 * /robot_description_planning/joint_limits/j5/max_velocity: 0.7
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.16
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator/kinematics_solver_attempts: 3
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator/kinematics_solver_search_resolution: 0.005
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator/kinematics_solver_timeout: 0.5
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator_flange/kinematics_solver: kdl_kinematics_pl...
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator_flange/kinematics_solver_attempts: 3
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator_flange/kinematics_solver_search_resolution: 0.005
 * /rviz_tork_kudu1_16771_1735429576353899133/manipulator_flange/kinematics_solver_timeout: 0.005

NODES
  /
    move_group (moveit_ros_move_group/move_group)
    pr2_controller_manager (pr2_controller_manager/spawner)
    realtime_loop (denso_controller/main)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_tork_kudu1_16771_1735429576353899133 (rviz/rviz)
    state_publisher (robot_state_publisher/state_publisher)

WARNING: [/opt/ros/indigo/share/denso_launch/launch/denso_vs060_startup_skelton.launch] unknown <node> attribute 'gdb-launch-prefix'
auto-starting new master
process[master]: started with pid [16783]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d4f99738-b4a2-11e5-8b7c-80fa5b08d1d8
process[rosout-1]: started with pid [16796]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [16813]
process[move_group-3]: started with pid [16814]
process[rviz_tork_kudu1_16771_1735429576353899133-4]: started with pid [16815]
[ WARN] [1452104716.579939867]: The root link BASE has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[realtime_loop-5]: started with pid [16821]
process[pr2_controller_manager-6]: started with pid [16837]
mlockall: Cannot allocate memory
process[state_publisher-7]: started with pid [16843]
[ INFO] [1452104716.599986926]: server: 133.11.216.51:5007
[ INFO] [1452104716.600629974]: udp_timeout: 9000 micro sec
[ WARN] [1452104716.604824391]: min_acceptable_rt_loop_frequency changed to 100.000000
[ INFO] [1452104716.605456567]: realtime loop period is 8000000.000000
[ INFO] [1452104716.606051747]: pidfile is: open_controller.pid
[ INFO] [1452104716.606616806]: piddir is: /var/tmp/run/
[ INFO] [1452104716.670917649]: rviz version 1.11.10
[ INFO] [1452104716.671035264]: compiled against OGRE version 1.8.1 (Byatis)
[ INFO] [1452104716.757673955]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1452104716.757792263]: No root joint specified. Assuming fixed joint
[ INFO] [1452104716.812121061]: success to initialize the controller manager
[ INFO] [1452104716.812256223]: bCapOpen
[ INFO] [1452104717.045668515]: Stereo is NOT SUPPORTED
[ INFO] [1452104717.045757538]: OpenGl version: 3 (GLSL 1.3).
[ INFO] [1452104717.298718672]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1452104717.298782725]: No root joint specified. Assuming fixed joint
[ WARN] [1452104717.567905243]: The root link BASE has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1452104717.572324932]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1452104717.572378727]: No root joint specified. Assuming fixed joint
[ERROR] [1452104717.840176157]: Group 'manipulator_flange' is not a chain
[ERROR] [1452104717.840250019]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'manipulator_flange'
[ERROR] [1452104717.840792823]: Kinematics solver could not be instantiated for joint group manipulator_flange.
[ INFO] [1452104717.909133217]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1452104717.911955475]: MoveGroup debug mode is OFF
Starting context monitors...
[ INFO] [1452104717.911995747]: Starting scene monitor
[ INFO] [1452104717.914666928]: Listening to '/planning_scene'
[ INFO] [1452104717.914698800]: Starting world geometry monitor
[ INFO] [1452104717.917254878]: Listening to '/collision_object' using message notifier with target frame '/BASE '
[ INFO] [1452104717.919858960]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1452104718.135690752]: Listening to '/camera/depth_registered/points' using message filter with target frame '/BASE '
[ INFO] [1452104718.141166437]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1452104718.258281092]: Initializing OMPL interface using ROS parameters
[ INFO] [1452104718.279853428]: Using planning interface 'OMPL'
[ INFO] [1452104718.379140928]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1452104718.379831754]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1452104718.380495006]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1452104718.381195640]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1452104718.381722554]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1452104718.382225169]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1452104718.382293569]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1452104718.382325952]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1452104718.382351099]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1452104718.382373456]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1452104718.382398679]: Using planning request adapter 'Fix Start State Path Constraints'
[ INFO] [1452104723.482171634]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1452104723.482236137]: No root joint specified. Assuming fixed joint
[ INFO] [1452104723.925682579]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1452104723.925731879]: No root joint specified. Assuming fixed joint
[ WARN] [1452104724.210279134]: The root link BASE has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1452104724.214501729]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1452104724.214548471]: No root joint specified. Assuming fixed joint
[ERROR] [1452104724.501939053]: Group 'manipulator_flange' is not a chain
[ERROR] [1452104724.502065718]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'manipulator_flange'
[ERROR] [1452104724.502574029]: Kinematics solver could not be instantiated for joint group manipulator_flange.
[ INFO] [1452104724.580049618]: Starting scene monitor
[ INFO] [1452104724.583413505]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1452104724.585176923]: waitForService: Service [/get_planning_scene] has not been advertised, waiting...
[ WARN] [1452104729.590806871]: Failed to call service /get_planning_scene, have you launched move_group? at /tmp/buildd/ros-indigo-moveit-ros-planning-0.6.5-0trusty-20151201-0131/planning_scene_monitor/src/planning_scene_monitor.cpp:461
[ WARN] [1452104729.613249246]: The root link BASE has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1452104729.619341152]: Constructing new MoveGroup connection for group 'manipulator' in namespace ''
[ERROR] [1452104759.666941252]: Unable to connect to move_group action server within allotted time (2)
[ WARN] [1452104844.032474528]: Something went wrong with lister service
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 161, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 139, in main
    resp = load_controller(name)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] [WallTime: 1452104844.041811] Spawner couldn't reach pr2_controller_manager to take down controllers.
[ INFO] [1452104844.050296882]: Trajectory execution is managing controllers
Loading 'move_group/MoveGroupCartesianPathService'...
[realtime_loop-5] process has died [pid 16821, exit code 1, cmd /opt/ros/indigo/lib/denso_controller/main -x /opt/ros/indigo/share/vs060/model/vs060A1_AV6_NNN_NNN.urdf -s __name:=realtime_loop __log:=/home/n130s/.ros/log/d4f99738-b4a2-11e5-8b7c-80fa5b08d1d8/realtime_loop-5.log].
log file: /home/n130s/.ros/log/d4f99738-b4a2-11e5-8b7c-80fa5b08d1d8/realtime_loop-5*.log
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1452104844.323784828]: 

********************************************************
* MoveGroup using: 
*     - CartesianPathService
*     - ExecutePathService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1452104844.323904344]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1452104844.323940802]: MoveGroup context initialization complete

All is well! Everyone is happy! You can start planning now!

[pr2_controller_manager-6] process has died [pid 16837, exit code 1, cmd /opt/ros/indigo/lib/pr2_controller_manager/spawner arm_controller __name:=pr2_controller_manager __log:=/home/n130s/.ros/log/d4f99738-b4a2-11e5-8b7c-80fa5b08d1d8/pr2_controller_manager-6.log].
log file: /home/n130s/.ros/log/d4f99738-b4a2-11e5-8b7c-80fa5b08d1d8/pr2_controller_manager-6*.log

$ rosnode list
/move_group
/pr2_controller_manager
/realtime_loop
/robot_state_publisher
/rosout
/rviz_tork_kudu1_16771_1735429576353899133
/state_publisher
```

**Comment by 130s** [comment]
Confirmed manually that this also happens with the previous version (1.1.1), so I guess it's likely rooted in somewhere upstream?

**Comment by 130s** [comment]
Current test suite doesn't capture this issue ([example](https://travis-ci.org/start-jsk/denso/builds/100693614)); I'm not sure yet if it's because the tests are inadequate, or because this issue is specific to a certain environment.

**Comment by 130s** [comment]
Marked as `invalid`.
Wrong launch file was used on simulation. With `$ roslaunch vs060_moveit_config demo_simulation_noenvironment.launch`, everything works fine.

#I believe with #73 we'll be able to catch (a silly) human error like this.
